/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizproject;

/**
 *
 * @author HP
 */
import java.awt.Container;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
public class Apti_1 extends javax.swing.JFrame {

    /**
     * Creates new form Pro_1
     */
    Container c;
    public static int count=0;
    public static int count2 =0;
    public static int apt =0;
    public Apti_1() {
        initComponents();
        c=getContentPane();
        c.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Q1c = new javax.swing.JRadioButton();
        Q1b = new javax.swing.JRadioButton();
        Q1a = new javax.swing.JRadioButton();
        Q1d = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Q2a = new javax.swing.JRadioButton();
        Q2d = new javax.swing.JRadioButton();
        Q2c = new javax.swing.JRadioButton();
        Q2b = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Q3b = new javax.swing.JRadioButton();
        Q3a = new javax.swing.JRadioButton();
        Q3d = new javax.swing.JRadioButton();
        Q3c = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Q4a = new javax.swing.JRadioButton();
        Q4d = new javax.swing.JRadioButton();
        Q5b = new javax.swing.JRadioButton();
        Q4c = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Q4b = new javax.swing.JRadioButton();
        Q5d = new javax.swing.JRadioButton();
        Q5a = new javax.swing.JRadioButton();
        Q5c = new javax.swing.JRadioButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Aptitude Ques Series");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel2.setText("If A is the brother of B, B is the sister of C, and C is the father of D, how is A related to D?");

        buttonGroup1.add(Q1c);
        Q1c.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q1c.setText("brother");

        buttonGroup1.add(Q1b);
        Q1b.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q1b.setText("father");

        buttonGroup1.add(Q1a);
        Q1a.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q1a.setText("uncle");

        buttonGroup1.add(Q1d);
        Q1d.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q1d.setText("grandfather");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel4.setText("Find the next number in the series: 2, 6, 12, 20, 30, ?");

        buttonGroup2.add(Q2a);
        Q2a.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q2a.setText("40");

        buttonGroup2.add(Q2d);
        Q2d.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q2d.setText("50");

        buttonGroup2.add(Q2c);
        Q2c.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q2c.setText("45");

        buttonGroup2.add(Q2b);
        Q2b.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q2b.setText("42");

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCEL");

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel5.setText("A clock is set to show the correct time at 12:00 noon. It gains 15 minutes in every 3 hours. ");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("What will be the correct time when the clock shows 9:00 PM?");

        buttonGroup3.add(Q3b);
        Q3b.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q3b.setText("8:30 PM");

        buttonGroup3.add(Q3a);
        Q3a.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q3a.setText("8:00 PM");

        buttonGroup3.add(Q3d);
        Q3d.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q3d.setText("7:00 PM");

        buttonGroup3.add(Q3c);
        Q3c.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q3c.setText("7:30 PM");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setText("If all the vowels in the word ‘NATIONAL’ are removed, which letters are left?");

        buttonGroup4.add(Q4a);
        Q4a.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q4a.setText(" N, T, N, A");
        Q4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4aActionPerformed(evt);
            }
        });

        buttonGroup4.add(Q4d);
        Q4d.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q4d.setText("N, L, N, T");

        buttonGroup5.add(Q5b);
        Q5b.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q5b.setText("South-East");

        buttonGroup4.add(Q4c);
        Q4c.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q4c.setText(" N, T, L");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("A is to the west of B, B is to the north of C, and C is to the east of D. In which direction is A with respect to D?");

        buttonGroup4.add(Q4b);
        Q4b.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q4b.setText("N,T,N,L");

        buttonGroup5.add(Q5d);
        Q5d.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q5d.setText("South-West");

        buttonGroup5.add(Q5a);
        Q5a.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q5a.setText("North-West");

        buttonGroup5.add(Q5c);
        Q5c.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Q5c.setText("North-East");

        l1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        l1.setText("1");

        l2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        l2.setText("2");

        l3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        l3.setText("3");

        l4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        l4.setText("4");

        l5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        l5.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(Q2a, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(Q2b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(Q2c, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(Q2d, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(Q1a)
                                .addGap(86, 86, 86)
                                .addComponent(Q1b)
                                .addGap(69, 69, 69)
                                .addComponent(Q1c)
                                .addGap(58, 58, 58)
                                .addComponent(Q1d))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(Q5a, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(Q5b, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(Q5c, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Q5d, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(Q4a, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(Q4b, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Q4c, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Q4d, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Q3a, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(Q3b, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(Q3c, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(Q3d, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1a)
                    .addComponent(Q1b)
                    .addComponent(Q1c)
                    .addComponent(Q1d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2a)
                    .addComponent(Q2c)
                    .addComponent(Q2b)
                    .addComponent(Q2d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Q3a)
                        .addComponent(Q3b)
                        .addComponent(Q3c)
                        .addComponent(Q3d))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Q4a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q4b)
                            .addComponent(Q4c)
                            .addComponent(Q4d))
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(l5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q5a)
                    .addComponent(Q5b)
                    .addComponent(Q5c)
                    .addComponent(Q5d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        count=0;
        count2=0;
        apt=0;
        
        int total=0;
         int qid=Integer.parseInt(l1.getText());
         String res="";
         if(Q1a.isSelected()==true)
         {
             res=Q1a.getText();
         }
         else if(Q1b.isSelected()==true)
         {
             res=Q1b.getText();
         }
         else if(Q1c.isSelected()==true)
         {
             res=Q1c.getText();
         }
         else if(Q1d.isSelected()==true)
         {
             res=Q1d.getText();
         }
         else if(Q1a.isSelected()==false && Q1b.isSelected() == false && Q1c.isSelected()==false && Q1d.isSelected()==false)
         {
             apt++;
         }
         
         int qid1=Integer.parseInt(l2.getText());
         String res1="";
         
         if(Q2a.isSelected()==true)
         {
             res1=Q2a.getText();
         }
         else if(Q2b.isSelected()==true)
         {
             res1=Q2b.getText();
         }
         else if(Q2c.isSelected()==true)
         {
             res1=Q2c.getText();
         }
         else if(Q2d.isSelected()==true)
         {
             res1=Q2d.getText();
         }
         else if(Q2a.isSelected()==false && Q2b.isSelected() == false && Q2c.isSelected()==false && Q2d.isSelected()==false)
         {
             apt++;
         }
         
         
         int qid2=Integer.parseInt(l3.getText());
         String res2="";
         if(Q3a.isSelected()==true)
         {
             res2=Q3a.getText();
         }
         else if(Q3b.isSelected()==true)
         {
             res2=Q3b.getText();
         }
         else if(Q3c.isSelected()==true)
         {
             res2=Q3c.getText();
         }
         else if(Q3d.isSelected()==true)
         {
             res2=Q3d.getText();
         }
         else if(Q3a.isSelected()==false && Q3b.isSelected() == false && Q3c.isSelected()==false && Q3d.isSelected()==false)
         {
             apt++;
         }
         
         int qid3=Integer.parseInt(l4.getText());
         String res3="";
         
         if(Q4a.isSelected()==true)
         {
             res3=Q4a.getText();
         }
         else if(Q4b.isSelected()==true)
         {
             res3=Q4b.getText();
         }
         else if(Q4c.isSelected()==true)
         {
             res3=Q4c.getText();
         }
         else if(Q4d.isSelected()==true)
         {
             res3=Q4d.getText();
         }
         else if(Q4a.isSelected()==false && Q4b.isSelected() == false && Q4c.isSelected()==false && Q4d.isSelected()==false)
         {
             apt++;
         }
         
         int qid4=Integer.parseInt(l5.getText());
         String res4="";
         if(Q5a.isSelected()==true)
         {
             res4=Q5a.getText();
         }
         else if(Q5b.isSelected()==true)
         {
             res4=Q5b.getText();
         }
         else if(Q5c.isSelected()==true)
         {
             res4=Q5c.getText();
         }
         else if(Q5d.isSelected()==true)
         {
             res4=Q5d.getText();
         }
         else if(Q5a.isSelected()==false && Q5b.isSelected() == false && Q5c.isSelected()==false && Q5d.isSelected()==false)
         {
             apt++;
         }
         
         int c=0;
         try{
            Connection con=ConnectionCode.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select Que_ID, Answer from Aptitude");
            while(rs.next() && c<5)
            {
               int qno=rs.getInt("Que_ID");
               String ans=rs.getString("Answer");
               c++;
               //System.out.println(ans);
               if(qno==qid && res.equals(ans) )
               {
                   count++;
               }
               else if(qno==qid1 && res1.equals(ans))
               {
                   count++;
               }
                else if(qno==qid2 && res2.equals(ans))
               {
                   count++;
               }
                else if(qno==qid3 && res3.equals(ans))
               {
                   count++;
               }
                else if(qno==qid4 && res4.equals(ans))
               {
                   count++;
               }
               else
                {
                    count2++;
                }
            
            }
             
            total=count*5;
            System.out.println("+ve score="+count);
            System.out.println("-ve score="+count2);
        /*System.out.println(res);
            System.out.println(res1);
            System.out.println(res2);
            System.out.println(res3);
            System.out.println(res4);*/
            
            System.out.println("total="+total);
           
            
        }catch(Exception e)
        {
            System.out.println(" ********** "+e);
        }
         
        this.toBack();
        Apti_2 t2=new Apti_2();
        t2.setVisible(true);
        t2.toFront();
        t2.setState(javax.swing.JFrame.NORMAL);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Q4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q4aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apti_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apti_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apti_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apti_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Apti_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Q1a;
    private javax.swing.JRadioButton Q1b;
    private javax.swing.JRadioButton Q1c;
    private javax.swing.JRadioButton Q1d;
    private javax.swing.JRadioButton Q2a;
    private javax.swing.JRadioButton Q2b;
    private javax.swing.JRadioButton Q2c;
    private javax.swing.JRadioButton Q2d;
    private javax.swing.JRadioButton Q3a;
    private javax.swing.JRadioButton Q3b;
    private javax.swing.JRadioButton Q3c;
    private javax.swing.JRadioButton Q3d;
    private javax.swing.JRadioButton Q4a;
    private javax.swing.JRadioButton Q4b;
    private javax.swing.JRadioButton Q4c;
    private javax.swing.JRadioButton Q4d;
    private javax.swing.JRadioButton Q5a;
    private javax.swing.JRadioButton Q5b;
    private javax.swing.JRadioButton Q5c;
    private javax.swing.JRadioButton Q5d;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    // End of variables declaration//GEN-END:variables
}
